INTERFACE zasis_if_version
  PUBLIC.

  CONSTANTS version TYPE string VALUE '0.4.0' ##NO_TEXT.
  CONSTANTS dummy TYPE string VALUE 'SYNC_TEST' ##NO_TEXT.
  CONSTANTS dummy2 TYPE string VALUE 'SYNC_TEST_2' ##NO_TEXT.
  CONSTANTS dummy3 TYPE string VALUE 'SYNC_TEST_3' ##NO_TEXT.

ENDINTERFACE.
